name: Diff-Insight LaTeX Review
on:
  pull_request:
    paths:
      - '**.tex'
      - '**.bib'
      - '**/figures/**'
      - '**/images/**'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git diff
      
      - name: Run Diff-Insight Analysis
        uses: diff-insight/diff-insight@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}  # Optional if using local LLM
          latex-diff: true
          max-diff-lines: 1000
          # Uncomment below to use local LLM
          # local-model-endpoint: 'http://localhost:11434/v1'
          # model: 'local-model'